* Makefile

Makefiles require TAB characters for recipe lines (commands under targets) - spaces will cause a "missing separator" error:

#+begin_src text :tangle no
Makefile:2: *** missing separator.  Stop.
#+end_src

So force tabs to avoid error:

#+begin_src elisp
(after! makefile-mode
  (setq-hook! 'makefile-mode-hook indent-tabs-mode t))
#+end_src
