* doom-emacs-config

[[https://github.com/hlissner/doom-emacs][Doom]] is faster than my personal Emacs config. Maybe it is worth to join the team.

The =.doom.d= folder is like a private Doom module.

A module can have a =packages.el= and a =config.el=, so: only use =package!= in
the former and =use-package!= in the latter. =use-package!= is formerly known as
=def-package!= (which is deprecated).

=package!= is declarative: meant only for telling Doom what this module's
dependencies are (and optionally, where to find them).

=!map= is a convenience macro for defining keybinds, powered by =general.el=.

** Inspiration

- [[https://tecosaur.github.io/emacs-config/config.html][Doom Emacs Configuration]]
- [[https://github.com/niklascarlsson/doom-private][GitHub - niklascarlsson/doom-private: My private module with tweaks for the Emacs Doom]]
- [[https://github.com/niklascarlsson/dotfiles][GitHub - niklascarlsson/dotfiles: My dotfiles]]
- [[https://gitlab.com/justinekizhak/dotfiles/blob/master/emacs/doom.d/config.org][emacs/doom.d/config.org · master · Justine Kizhakkinedath / dotfiles · GitLab]]
- [[https://github.com/Brettm12345/doom-emacs-literate-config/blob/master/config.org][doom-emacs-literate-config/config.org]]

** TODO Implement stuff

- [X] Add =reformatter.el=
- [ ] Add reformatter hooks
- [X] Treemacs should use =.gitignore= to hide files
- [X] Add =tmux= pane dump function
- [X] Add the package for =zoom-mode=
- [X] Add =ox-hugo=
- [X] Add =org-roam=
- [X] Open with =mpv= from =dired=

Here is a code block:

#+BEGIN_SRC emacs-lisp
(message "hello")
#+END_SRC

#+RESULTS:
: hello

** TODO Notes

*** Good

Doom uses =straight.el= and =general.el= under the hood. They are hiding behind:

- =package!=
- =map!=

Packages are not updated on startup - you have to run =doom sync= from your CLI
to invoke it. They pin every package to a hash. I like that. It is better than
what I had. =doom sync= even supports literate configs. I like that the pinning
is done in =packages.el= of the module.

I like that the docs mention [[https://github.com/hlissner/doom-emacs/tree/develop/modules/config/literate#modularizing-your-literate-config-with-include-directives][include directives]].

I already found stuff for =tmux= I was about to create in my own config:

- =+tmux/cd-to-here=
- =+tmux/send-region=

See [[https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/tmux/autoload/tmux.el][/modules/tools/tmux]].

The exploration has already paid for itself.

I like having =tmux= running in a WM scratchpad.

=magit= seems to work fine (=SPC g g=). I like that it goes into fullscreen.

I like the way it make Emacs look.

I like that navigating Org files is snappy. In my config, cycling with =TAB= is
somewhat slow.

I like that you can switch themes on the fly without breaking all the colors
everything.

I like the =doom-one-light= theme.

I like that =magit= commit goes straight into insert mode and I can =C-c C-c=
without leaving insert mode.

I like all the custom link types included with Org mode.

=(dired +icons)= is nice.

I like the concept of modules and feature flags.

I like =SPC t z= (toggle zen) for =writeroom-mode= but I am not a big fan of the fonts
being used.

*** Bad

I wish I knew how to create my own modules and features.

I don't understand why =SPC n d= is mapped to =deft=, but =deft= is not
installed.

I don't like how the Python Language Server works out of the box.

I don't like all the keybindings, so I have to figure out how to change them. I
don't know how to change them and the documentation assumes I understand the
Doom structure. It should be fine once I look at some configs from other people.

I don't understand how to cleanly add a package.

I don't understand how to cleanly change settings and keybindings for included
packages.

I don't think I need line numbers.

Definition of *clean*: To follow the same organizational principles that Doom
employs. The whole reason for switching to Doom is to adopt a clean architecture
that improves on what I already have.
