* doom-emacs-config

[[https://github.com/hlissner/doom-emacs][Doom]] is faster than my personal Emacs config. Maybe it is worth to join the team.

** TODO Implement stuff

- Add =marklink= function
- Add programming reformatter hooks
- Treemacs should use =.gitignore= to hide files
- Add =tmux= pane dump function
- Add the package for =zoom-mode=
- [X] Add =ox-hugo=
- [ ] Add =org-roam=
  - I don't understand
- [ ] Open with =mpv= from =dired=

Here is a code block:

#+BEGIN_SRC emacs-lisp
(message "hello")
#+END_SRC

#+RESULTS:
: hello

** TODO Notes

*** Good

Doom uses =straight.el= under the hood. Packages are not updated on startup -
you have to run =doom sync= from your CLI to invoke it. They pin every package
to a hash. I like that. It is better than what I had. =doom sync= even supports
literate configs.

I already found stuff for =tmux= I was about to create in my own config:

- =+tmux/cd-to-here=
- =+tmux/send-region=

The exploration has already paid for itself.

I like having =tmux= running in a WM scratchpad.

=magit= seems to work fine (=SPC g g=). I like that it goes into fullscreen.

I like the way it make Emacs look.

I like that navigating Org files is snappy. In my config, cycling with =TAB= is
somewhat slow.

I like that you can switch themes on the fly without breaking all the colors
everything.

I like the =doom-one-light= theme.

I like that =magit= commit goes straight into insert mode and I can =C-c C-c=
without leaving insert mode.

I like all the custom link types included with Org mode.

=(dired +icons)= is nice.

I like the concept of modules and feature flags.

*** Bad

I wish I knew how to create my own modules and features.

I don't understand why =SPC n d= is mapped to =deft=, but =deft= is not
installed.

I don't like how the Python Language Server works out of the box.

I don't like all the keybindings, so I have to figure out how to change them. I
don't know how to change them and the documentation assumes I understand the
Doom structure. It should be fine once I look at some configs from other people.

I don't understand how to cleanly add a package.

I don't understand how to cleanly change settings and keybindings for included
packages.

I don't think I need line numbers.

Definition of *clean*: To follow the same organizational principles that Doom
employs. The whole reason for switching to Doom is to adopt a clean architecture
that improves on what I already have.


*** =org-roam=

Lets...

[[file:../org/roam/20200822132852-what.org][What]]
